### PR TITLE
Feature/2

### PR DESCRIPTION
**Pull request by brucewrks**
See: #2

### CODE REVIEW

**Comment by raamdev** [comment]
@brucewsinc I just reviewed this. Nice work!

I didn't see anywhere that you were implicitly specifying the sort order when retrieving `/issues` from GitHub. It seems like you're assuming that [`issues[0]`](https://github.com/websharks/ws-commander/pull/3/files#diff-098e3ee1b4abaab6246ccb671846972aR61) will be the _newest_ Issue in the repo (which is what we want). If the sort order of the results returned from the query are not newest to oldest (if they were sorted in order of, say, most recently updated, or most commented on) then `issues[0]` wouldn't contain the newest issue number and the calculation of `issues[0].number + 1` would be wrong... 

Am I missing something here?

**Comment by brucewrks** [comment]
@raamdev 

> If the sort order of the results returned from the query are not newest to oldest (if they were sorted in order of, say, most recently updated, or most commented on) then issues[0] wouldn't contain the newest issue number and the calculation of issues[0].number + 1 would be wrong...

I thought the same thing here, but that's not how Issues are sorted, apparently. I tested this and `issues[0]` is the newest Issue. For instance, after I commented on [this Issue](https://github.com/websharks/ws-commander/issues/1), I ran this:

```
Bruces-Mac-mini:~ bruce$ ws github next-issue-url https://github.com/websharks/ws-commander/issues/new
https://github.com/websharks/ws-commander/issues/4
```

It ignored the fact that I commented on the Issue, and picked up on the Pull Request for the feature branch #2 (this Issue).

If we can find a case that this doesn't work correctly, then I will add additional processing, but it looks like it works just fine like this.

**Comment by raamdev** [comment]
Why don't we just set `?sort=created&direction=desc` and be done with it? That way there's no guessing involved. https://developer.github.com/v3/issues/#list-issues-for-a-repository

**Comment by brucewrks** [comment]
> Why don't we just set ?sort=created&direction=desc and be done with it? That way there's no guessing involved. https://developer.github.com/v3/issues/#list-issues-for-a-repository

Perfect :+1:

**Comment by raamdev** [comment]
``` js
path    : '/repos/' + owner.toLowerCase() + '/' + repo.toLowerCase() + '/issues?sort=created&direction=desc',
```

**Comment by brucewrks** [comment]
@raamdev Thanks for the help! I'm going to merge this shortly.

**Pull request merged**
